// <auto-generated />
using System;
using EcoClean.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoClean.API.Migrations
{
    [DbContext(typeof(EcoCleanDbContext))]
    [Migration("20260528120931_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoClean.API.Models.AIMealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AIMealPlans");
                });

            modelBuilder.Entity("EcoClean.API.Models.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SessionId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("EcoClean.API.Models.FoodScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<float?>("Carb")
                        .HasColumnType("real");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real");

                    b.Property<float?>("Fat")
                        .HasColumnType("real");

                    b.Property<string>("FoodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Protein")
                        .HasColumnType("real");

                    b.Property<string>("RawAIResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FoodScans");
                });

            modelBuilder.Entity("EcoClean.API.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "PlanDate");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("EcoClean.API.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<float>("Carb")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Fat")
                        .HasColumnType("real");

                    b.Property<float>("Fiber")
                        .HasColumnType("real");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrepTimeMin")
                        .HasColumnType("int");

                    b.Property<float>("Protein")
                        .HasColumnType("real");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 320,
                            Carb = 12f,
                            Category = "Lunch",
                            CreatedAt = new DateTime(2026, 5, 28, 12, 9, 30, 76, DateTimeKind.Utc).AddTicks(6062),
                            Fat = 14f,
                            Fiber = 4f,
                            IsActive = true,
                            Name = "Salad ức gà nướng",
                            Protein = 35f,
                            Tags = "[\"high-protein\",\"low-carb\"]"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 280,
                            Carb = 52f,
                            Category = "Breakfast",
                            CreatedAt = new DateTime(2026, 5, 28, 12, 9, 30, 76, DateTimeKind.Utc).AddTicks(6065),
                            Fat = 5f,
                            Fiber = 6f,
                            IsActive = true,
                            Name = "Yến mạch trái cây",
                            Protein = 8f,
                            Tags = "[\"fiber\",\"energy\"]"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 450,
                            Carb = 48f,
                            Category = "Lunch",
                            CreatedAt = new DateTime(2026, 5, 28, 12, 9, 30, 76, DateTimeKind.Utc).AddTicks(6067),
                            Fat = 12f,
                            Fiber = 5f,
                            IsActive = true,
                            Name = "Cơm gạo lứt cá hồi",
                            Protein = 42f,
                            Tags = "[\"omega3\",\"balanced\"]"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 380,
                            Carb = 38f,
                            Category = "Snack",
                            CreatedAt = new DateTime(2026, 5, 28, 12, 9, 30, 76, DateTimeKind.Utc).AddTicks(6068),
                            Fat = 20f,
                            Fiber = 6f,
                            IsActive = true,
                            Name = "Smoothie bơ chuối",
                            Protein = 12f,
                            Tags = "[\"smoothie\",\"healthy-fat\"]"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 210,
                            Carb = 6f,
                            Category = "Breakfast",
                            CreatedAt = new DateTime(2026, 5, 28, 12, 9, 30, 76, DateTimeKind.Utc).AddTicks(6069),
                            Fat = 13f,
                            Fiber = 2f,
                            IsActive = true,
                            Name = "Trứng bác rau cải",
                            Protein = 18f,
                            Tags = "[\"low-carb\",\"quick\"]"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 290,
                            Carb = 14f,
                            Category = "Dinner",
                            CreatedAt = new DateTime(2026, 5, 28, 12, 9, 30, 76, DateTimeKind.Utc).AddTicks(6071),
                            Fat = 6f,
                            Fiber = 5f,
                            IsActive = true,
                            Name = "Gà luộc rau hấp",
                            Protein = 40f,
                            Tags = "[\"lean\",\"clean\"]"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 310,
                            Carb = 44f,
                            Category = "Breakfast",
                            CreatedAt = new DateTime(2026, 5, 28, 12, 9, 30, 76, DateTimeKind.Utc).AddTicks(6072),
                            Fat = 8f,
                            Fiber = 8f,
                            IsActive = true,
                            Name = "Overnight oats",
                            Protein = 14f,
                            Tags = "[\"prep-ahead\",\"fiber\"]"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 400,
                            Carb = 42f,
                            Category = "Dinner",
                            CreatedAt = new DateTime(2026, 5, 28, 12, 9, 30, 76, DateTimeKind.Utc).AddTicks(6074),
                            Fat = 10f,
                            Fiber = 5f,
                            IsActive = true,
                            Name = "Bowl cá ngừ quinoa",
                            Protein = 38f,
                            Tags = "[\"complete-protein\",\"grain\"]"
                        });
                });

            modelBuilder.Entity("EcoClean.API.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("EcoClean.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PremiumExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoClean.API.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<float>("BMI")
                        .HasColumnType("real");

                    b.Property<string>("BMICategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<float>("TDEE")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("EcoClean.API.Models.WeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LogDate");

                    b.ToTable("WeightLogs");
                });

            modelBuilder.Entity("EcoClean.API.Models.AIMealPlan", b =>
                {
                    b.HasOne("EcoClean.API.Models.User", "User")
                        .WithMany("AIMealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoClean.API.Models.ChatHistory", b =>
                {
                    b.HasOne("EcoClean.API.Models.User", "User")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoClean.API.Models.FoodScan", b =>
                {
                    b.HasOne("EcoClean.API.Models.User", "User")
                        .WithMany("FoodScans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoClean.API.Models.MealPlan", b =>
                {
                    b.HasOne("EcoClean.API.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoClean.API.Models.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoClean.API.Models.Subscription", b =>
                {
                    b.HasOne("EcoClean.API.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoClean.API.Models.UserProfile", b =>
                {
                    b.HasOne("EcoClean.API.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("EcoClean.API.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoClean.API.Models.WeightLog", b =>
                {
                    b.HasOne("EcoClean.API.Models.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoClean.API.Models.User", b =>
                {
                    b.Navigation("AIMealPlans");

                    b.Navigation("ChatHistories");

                    b.Navigation("FoodScans");

                    b.Navigation("MealPlans");

                    b.Navigation("Profile");

                    b.Navigation("Subscriptions");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
